export const START_CTIIES_INFO = "START_CTIIES_INFO";
export const FETCH_CITIES_INFO = "FETCH_CITIES_INFO";
export const FAILED_CITIES_INFO = "FAILED_CITIES_INFO";
export const START_TEMP_INFO = "START_TEMP_INFO";
export const FETCH_TEMP_INFO = "FETCH_TEMP_INFO";
export const FAILED_TEMP_INFO = "FAILED_TEMP_INFO";